# Assessment 1: Group 6

**Abrigo, Nathanael Chris**

**Buhay, Kyle Andrei**

**Entrata, Joshua Kyle**

**Cruz, Lenci Kristel**

## `Part 1: Data Wrangling`

### Data Cleaning

In [40]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

**Loading Datasets**

In [41]:
df_fao = pd.read_csv('data/FAO.csv', encoding='iso-8859-1')
df_faostat = pd.read_csv('data/FAOSTAT.csv')

**Data Dictionary**

**FAO Dataset Dictionary**

In [42]:
df_fao.head()

,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
0,AFG,2,Afghanistan,2511,Wheat and products,5142,Food,1000 tonnes,33.94,67.71,1928.0,1904.0,1666.0,1950.0,2001.0,1808.0,2053.0,2045.0,2154.0,1819.0,1963.0,2215.0,2310.0,2335.0,2434.0,2512.0,2282.0,2454.0,2443.0,2129.0,2133.0,2068.0,1994.0,1851.0,1791.0,1683.0,2194.0,1801.0,1754.0,1640.0,1539.0,1582.0,1840.0,1855.0,1853.0,2177.0,2343.0,2407.0,2463.0,2600.0,2668.0,2776.0,3095.0,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895
1,AFG,2,Afghanistan,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,33.94,67.71,183.0,183.0,182.0,220.0,220.0,195.0,231.0,235.0,238.0,213.0,205.0,233.0,246.0,246.0,255.0,263.0,235.0,254.0,270.0,259.0,248.0,217.0,217.0,197.0,186.0,200.0,193.0,202.0,191.0,199.0,197.0,249.0,218.0,260.0,319.0,254.0,326.0,347.0,270.0,372.0,411.0,448.0,460.0,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422
2,AFG,2,Afghanistan,2513,Barley and products,5521,Feed,1000 tonnes,33.94,67.71,76.0,76.0,76.0,76.0,76.0,75.0,71.0,72.0,73.0,74.0,71.0,70.0,72.0,76.0,77.0,80.0,60.0,65.0,64.0,64.0,60.0,55.0,53.0,51.0,48.0,46.0,46.0,47.0,46.0,43.0,43.0,40.0,50.0,46.0,41.0,44.0,50.0,48.0,43.0,26.0,29.0,70.0,48.0,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360
3,AFG,2,Afghanistan,2513,Barley and products,5142,Food,1000 tonnes,33.94,67.71,237.0,237.0,237.0,238.0,238.0,237.0,225.0,227.0,230.0,234.0,223.0,219.0,225.0,240.0,244.0,255.0,185.0,203.0,198.0,202.0,189.0,174.0,167.0,160.0,151.0,145.0,145.0,148.0,145.0,135.0,132.0,120.0,155.0,143.0,125.0,138.0,159.0,154.0,141.0,84.0,83.0,122.0,144.0,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89
4,AFG,2,Afghanistan,2514,Maize and products,5521,Feed,1000 tonnes,33.94,67.71,210.0,210.0,214.0,216.0,216.0,216.0,235.0,232.0,236.0,200.0,201.0,216.0,228.0,231.0,234.0,240.0,228.0,234.0,228.0,226.0,210.0,199.0,192.0,182.0,173.0,170.0,154.0,148.0,137.0,144.0,126.0,90.0,141.0,150.0,159.0,108.0,90.0,99.0,72.0,35.0,48.0,89.0,63.0,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200

In [43]:
df_fao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21477 entries, 0 to 21476
Data columns (total 63 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Area Abbreviation  21477 non-null  object
 1   Area Code          21477 non-null  int64
 2   Area               21477 non-null  object
 3   Item Code          21477 non-null  int64
 4   Item               21477 non-null  object
 5   Element Code       21477 non-null  int64
 6   Element            21477 non-null  object
 7   Unit               21477 non-null  object
 8   latitude           21477 non-null  float64
 9   longitude          21477 non-null  float64
 10  Y1961              17938 non-null  float64
 11  Y1962              17938 non-null  float64
 12  Y1963              17938 non-null  float64
 13  Y1964              17938 non-null  float64
 14  Y1965              17938 non-null  float64
 15  Y1966              17938 non-null  float64
 16  Y1967              17938 non-null  float64
 17  Y1968              17938 non-null  float64
 18  Y1969              17938 non-null  float64
 19  Y1970              17938 non-null  float64
 20  Y1971              17938 non-null  float64
 21  Y1972              17938 non-null  float64
 22  Y1973              17938 non-null  float64
 23  Y1974              17938 non-null  float64
 24  Y1975              17938 non-null  float64
 25  Y1976              17938 non-null  float64
 26  Y1977              17938 non-null  float64
 27  Y1978              17938 non-null  float64
 28  Y1979              17938 non-null  float64
 29  Y1980              17938 non-null  float64
 30  Y1981              17938 non-null  float64
 31  Y1982              17938 non-null  float64
 32  Y1983              17938 non-null  float64
 33  Y1984              17938 non-null  float64
 34  Y1985              17938 non-null  float64
 35  Y1986              17938 non-null  float64
 36  Y1987              17938 non-null  float64
 37  Y1988              17938 non-null  float64
 38  Y1989              17938 non-null  float64
 39  Y1990              18062 non-null  float64
 40  Y1991              18062 non-null  float64
 41  Y1992              20490 non-null  float64
 42  Y1993              20865 non-null  float64
 43  Y1994              20865 non-null  float64
 44  Y1995              20865 non-null  float64
 45  Y1996              20865 non-null  float64
 46  Y1997              20865 non-null  float64
 47  Y1998              20865 non-null  float64
 48  Y1999              20865 non-null  float64
 49  Y2000              21128 non-null  float64
 50  Y2001              21128 non-null  float64
 51  Y2002              21128 non-null  float64
 52  Y2003              21128 non-null  float64
 53  Y2004              21128 non-null  float64
 54  Y2005              21128 non-null  float64
 55  Y2006              21373 non-null  float64
 56  Y2007              21373 non-null  float64
 57  Y2008              21373 non-null  float64
 58  Y2009              21373 non-null  float64
 59  Y2010              21373 non-null  float64
 60  Y2011              21373 non-null  float64
 61  Y2012              21477 non-null  int64
 62  Y2013              21477 non-null  int64
dtypes: float64(53), int64(5), object(5)
memory usage: 10.3+ MB

In [44]:
# Create a list of descriptions in the same order as the columns
description_list = [
    'Abbreviation of Area',
    'Full name of the country or region',
    'ISO country code or region abbreviation',
    'Numeric code for the country or region',
    'Numeric code for the item',
    'Name of the food item or product',
    'Numeric code for the element',
    'Type of data recorded',
    'Measurement unit for the recorded data',
    'Latitude coordinate of the location',
    'Longitude coordinate of the location',
]

# Function to generate a data dictionary
def generate_data_dictionary(df):
    data_dict = {
        'Column Name': [],
        'Data Type': [],
        'Description': []
    }
    
    for i, column in enumerate(df.columns):
        data_dict['Column Name'].append(column)
        data_dict['Data Type'].append(df[column].dtype)
        # Provide a description based on the description list or a default value
        description = description_list[i] if i < len(description_list) else 'N/A'
        # If the column name starts with 'Y' and is a year, format accordingly
        if column.startswith('Y') and column[1:].isdigit():
            description = f'Data for the year {column[1:]}.'
        data_dict['Description'].append(description)
    
    return pd.DataFrame(data_dict)
    
# Generate the data dictionary
fao_data_dict = generate_data_dictionary(df_fao)

# Display the data dictionary
fao_data_dict

          Column Name Data Type                              Description
0   Area Abbreviation    object                     Abbreviation of Area
1           Area Code     int64       Full name of the country or region
2                Area    object  ISO country code or region abbreviation
3           Item Code     int64   Numeric code for the country or region
4                Item    object                Numeric code for the item
..                ...       ...                                      ...
58              Y2009   float64                  Data for the year 2009.
59              Y2010   float64                  Data for the year 2010.
60              Y2011   float64                  Data for the year 2011.
61              Y2012     int64                  Data for the year 2012.
62              Y2013     int64                  Data for the year 2013.

[63 rows x 3 columns]

**FAOSTAT Dataset Dictionary**

In [45]:
df_faostat.head()

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,OA,Annual population,2,Afghanistan,511,Total Population - Both sexes,3010,Population - Est. & Proj.,2017,2017,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population..."
1,OA,Annual population,3,Albania,511,Total Population - Both sexes,3010,Population - Est. & Proj.,2017,2017,1000 persons,2930.187,X,International reliable sources,"UNDESA, Population Division – World Population..."
2,OA,Annual population,4,Algeria,511,Total Population - Both sexes,3010,Population - Est. & Proj.,2017,2017,1000 persons,41318.142,X,International reliable sources,"UNDESA, Population Division – World Population..."
3,OA,Annual population,5,American Samoa,511,Total Population - Both sexes,3010,Population - Est. & Proj.,2017,2017,1000 persons,55.641,X,International reliable sources,"UNDESA, Population Division – World Population..."
4,OA,Annual population,6,Andorra,511,Total Population - Both sexes,3010,Population - Est. & Proj.,2017,2017,1000 persons,76.965,X,International reliable sources,"UNDESA, Population Division – World Population..."

In [46]:
df_faostat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231 entries, 0 to 230
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       231 non-null    object
 1   Domain            231 non-null    object
 2   Area Code         231 non-null    int64
 3   Area              231 non-null    object
 4   Element Code      231 non-null    int64
 5   Element           231 non-null    object
 6   Item Code         231 non-null    int64
 7   Item              231 non-null    object
 8   Year Code         231 non-null    int64
 9   Year              231 non-null    int64
 10  Unit              231 non-null    object
 11  Value             231 non-null    float64
 12  Flag              231 non-null    object
 13  Flag Description  231 non-null    object
 14  Note              231 non-null    object
dtypes: float64(1), int64(5), object(9)
memory usage: 27.2+ KB

In [47]:
# Create a mapping for descriptions based on column names
description_mapping=[
    'Numeric Code for Domain',
    'Population Type',
    'Numeric code for the country or region',
    'Full name of the country or region',
    'Numeric code for the element',
    'Population Sexes',
    'Numeric code for the item',
    'Name of the food item or product',
    'Code for the Year',
    'Time of the Year',
    'Quantity of item',
    'Value of the data',
    'Flag',
    'Sources of item',
    'Note for item',
]

#loop to insert column name of faostat in data_dict
j = 0 # Initialize a counter
# Create an empty list to store the data for the DataFrame
data = []
for i in df_faostat.columns:
  # Append a dictionary containing the data for each row to the list
  data.append({'Column Name': i, 'Data Type': df_faostat[i].dtype, 'Data Description': description_mapping[j]})
  j += 1 # Increment the counter after each iteration
    
# Create the DataFrame from the list of dictionaries
faostat_data_dict = pd.DataFrame(data)

# Display the data dictionary
faostat_data_dict

         Column Name Data Type                        Data Description
0        Domain Code    object                 Numeric Code for Domain
1             Domain    object                         Population Type
2          Area Code     int64  Numeric code for the country or region
3               Area    object      Full name of the country or region
4       Element Code     int64            Numeric code for the element
5            Element    object                        Population Sexes
6          Item Code     int64               Numeric code for the item
7               Item    object        Name of the food item or product
8          Year Code     int64                       Code for the Year
9               Year     int64                        Time of the Year
10              Unit    object                        Quantity of item
11             Value   float64                       Value of the data
12              Flag    object                                    Flag
13  Flag Description    object                         Sources of item
14              Note    object                           Note for item

**Handle Missing Values**

In [48]:
# Checking the number of rows with null value per column
fao_null_values = {}

for column in df_fao.columns:
    if df_fao[column].isnull().sum() > 0:
        fao_null_values[column] = df_fao[column].isnull().sum()
    
fao_null_values

{'Y1961': 3539,
 'Y1962': 3539,
 'Y1963': 3539,
 'Y1964': 3539,
 'Y1965': 3539,
 'Y1966': 3539,
 'Y1967': 3539,
 'Y1968': 3539,
 'Y1969': 3539,
 'Y1970': 3539,
 'Y1971': 3539,
 'Y1972': 3539,
 'Y1973': 3539,
 'Y1974': 3539,
 'Y1975': 3539,
 'Y1976': 3539,
 'Y1977': 3539,
 'Y1978': 3539,
 'Y1979': 3539,
 'Y1980': 3539,
 'Y1981': 3539,
 'Y1982': 3539,
 'Y1983': 3539,
 'Y1984': 3539,
 'Y1985': 3539,
 'Y1986': 3539,
 'Y1987': 3539,
 'Y1988': 3539,
 'Y1989': 3539,
 'Y1990': 3415,
 'Y1991': 3415,
 'Y1992': 987,
 'Y1993': 612,
 'Y1994': 612,
 'Y1995': 612,
 'Y1996': 612,
 'Y1997': 612,
 'Y1998': 612,
 'Y1999': 612,
 'Y2000': 349,
 'Y2001': 349,
 'Y2002': 349,
 'Y2003': 349,
 'Y2004': 349,
 'Y2005': 349,
 'Y2006': 104,
 'Y2007': 104,
 'Y2008': 104,
 'Y2009': 104,
 'Y2010': 104,
 'Y2011': 104}

In [49]:
faostat_null_values = {}

for column in df_faostat.columns:
    if df_faostat[column].isnull().sum() > 0:
        faostat_null_values[column] = df_faostat[column].isnull().sum()
    
faostat_null_values

{}

In [50]:
# checking of rows with null values
pd.set_option('display.max_columns', None)
df_fao[df_fao.isnull().any(axis=1)].head()

,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
679,ARM,1,Armenia,2511,Wheat and products,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,21.0,24.0,25.0,10.0,32.0,58.0,55.0,78.0,20.0,20.0,42.0,69.0,59.0,46.0,67.0,57.0,56.0,61.0,65.0,92,93
680,ARM,1,Armenia,2511,Wheat and products,5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,539.0,544.0,476.0,497.0,455.0,503.0,495.0,489.0,481.0,461.0,429.0,443.0,490.0,433.0,445.0,412.0,428.0,391.0,372.0,386.0,377,389
681,ARM,1,Armenia,2805,Rice (Milled Equivalent),5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
682,ARM,1,Armenia,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,19.0,17.0,10.0,10.0,7.0,11.0,10.0,10.0,9.0,13.0,12.0,11.0,14.0,17.0,15.0,13.0,13.0,11.0,9.0,9,9
683,ARM,1,Armenia,2513,Barley and products,5521,Feed,1000 tonnes,40.07,45.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.0,63.0,58.0,61.0,79.0,31.0,48.0,46.0,15.0,65.0,40.0,53.0,68.0,57.0,33.0,86.0,76.0,102.0,86.0,124.0,121,137

In [51]:
print(f'Number of rows with null values: {len(df_fao[df_fao.isnull().any(axis=1)])}')

Number of rows with null values: 3539

In [52]:
# fill null values with -1
for col in fao_null_values:
    df_fao[col] = df_fao[col].fillna(-1)

df_fao.iloc[[679]]

,Area Abbreviation,Area Code,Area,Item Code,Item,Element Code,Element,Unit,latitude,longitude,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
679,ARM,1,Armenia,2511,Wheat and products,5521,Feed,1000 tonnes,40.07,45.04,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,14.0,21.0,24.0,25.0,10.0,32.0,58.0,55.0,78.0,20.0,20.0,42.0,69.0,59.0,46.0,67.0,57.0,56.0,61.0,65.0,92,93

We handled missing data in the FAO and FAOSTAT dataset specifically for the years 1961 - 2021 by assigning a value of -1 to these missing entries. Instead of removing columns with NaN values, which could lead to losing potentially valuable data, we chose this method to ensure that the integrity of our dataset is maintained.

Assigning -1 helps in distinguishing missing data from actual zero values, which is crucial for accurate data analysis and visualization. Zero values and -1 are treated differently in plots; zeros might be misinterpreted as actual measurements or valid data points, while -1 clearly indicates that the data is missing. This approach prevents misleading visualizations where missing values might be inaccurately represented as zeroes, thus maintaining the clarity and reliability of the plots.

**Remove Duplicates**

In [53]:
# Duplicates in FAO
dupe_fao = df_fao.duplicated()

# Count duplicates in FA
dupe_fao_sum= dupe_fao.sum()

# Print total
print(f'Total number of duplicated rows in FAO: {dupe_fao_sum}')

# Duplicates in FAOSTAT
dupe_faostat = df_faostat.duplicated()

dupe_faostat_sum = dupe_faostat.sum()

print(f'Total number of duplicated rows in FAOSTAT: {dupe_faostat_sum}')

Total number of duplicated rows in FAO: 0
Total number of duplicated rows in FAOSTAT: 0

**Standardize column names**

In [54]:
df_fao.columns = (
    df_fao.columns
    .str.lower()                                 # Convert to lowercase
    .str.replace(' ', '_')                       # Replace spaces with underscores
    .str.replace(r'[^a-z0-9_]', '', regex=True)  # Remove special characters
)

df_faostat.columns = (
    df_faostat.columns
    .str.lower()                
    .str.replace(' ', '_')      
    .str.replace(r'[^a-z0-9_]', '', regex=True)  
)

#TODO: Rename the column names that are similar in both FAO and FAOSTAT

### Data Merging

**Merging**

In [55]:
df_fao.merge(
    df_faostat, 
    how='left', 
    on=['area_code', 'area']
)

,area_abbreviation,area_code,area,item_code_x,item_x,element_code_x,element_x,unit_x,latitude,longitude,y1961,y1962,y1963,y1964,y1965,y1966,y1967,y1968,y1969,y1970,y1971,y1972,y1973,y1974,y1975,y1976,y1977,y1978,y1979,y1980,y1981,y1982,y1983,y1984,y1985,y1986,y1987,y1988,y1989,y1990,y1991,y1992,y1993,y1994,y1995,y1996,y1997,y1998,y1999,y2000,y2001,y2002,y2003,y2004,y2005,y2006,y2007,y2008,y2009,y2010,y2011,y2012,y2013,domain_code,domain,element_code_y,element_y,item_code_y,item_y,year_code,year,unit_y,value,flag,flag_description,note
0,AFG,2,Afghanistan,2511,Wheat and products,5142,Food,1000 tonnes,33.94,67.71,1928.0,1904.0,1666.0,1950.0,2001.0,1808.0,2053.0,2045.0,2154.0,1819.0,1963.0,2215.0,2310.0,2335.0,2434.0,2512.0,2282.0,2454.0,2443.0,2129.0,2133.0,2068.0,1994.0,1851.0,1791.0,1683.0,2194.0,1801.0,1754.0,1640.0,1539.0,1582.0,1840.0,1855.0,1853.0,2177.0,2343.0,2407.0,2463.0,2600.0,2668.0,2776.0,3095.0,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population..."
1,AFG,2,Afghanistan,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,33.94,67.71,183.0,183.0,182.0,220.0,220.0,195.0,231.0,235.0,238.0,213.0,205.0,233.0,246.0,246.0,255.0,263.0,235.0,254.0,270.0,259.0,248.0,217.0,217.0,197.0,186.0,200.0,193.0,202.0,191.0,199.0,197.0,249.0,218.0,260.0,319.0,254.0,326.0,347.0,270.0,372.0,411.0,448.0,460.0,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population..."
2,AFG,2,Afghanistan,2513,Barley and products,5521,Feed,1000 tonnes,33.94,67.71,76.0,76.0,76.0,76.0,76.0,75.0,71.0,72.0,73.0,74.0,71.0,70.0,72.0,76.0,77.0,80.0,60.0,65.0,64.0,64.0,60.0,55.0,53.0,51.0,48.0,46.0,46.0,47.0,46.0,43.0,43.0,40.0,50.0,46.0,41.0,44.0,50.0,48.0,43.0,26.0,29.0,70.0,48.0,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population..."
3,AFG,2,Afghanistan,2513,Barley and products,5142,Food,1000 tonnes,33.94,67.71,237.0,237.0,237.0,238.0,238.0,237.0,225.0,227.0,230.0,234.0,223.0,219.0,225.0,240.0,244.0,255.0,185.0,203.0,198.0,202.0,189.0,174.0,167.0,160.0,151.0,145.0,145.0,148.0,145.0,135.0,132.0,120.0,155.0,143.0,125.0,138.0,159.0,154.0,141.0,84.0,83.0,122.0,144.0,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population..."
4,AFG,2,Afghanistan,2514,Maize and products,5521,Feed,1000 tonnes,33.94,67.71,210.0,210.0,214.0,216.0,216.0,216.0,235.0,232.0,236.0,200.0,201.0,216.0,228.0,231.0,234.0,240.0,228.0,234.0,228.0,226.0,210.0,199.0,192.0,182.0,173.0,170.0,154.0,148.0,137.0,144.0,126.0,90.0,141.0,150.0,159.0,108.0,90.0,99.0,72.0,35.0,48.0,89.0,63.0,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21472,ZWE,181,Zimbabwe,2948,Milk - Excluding Butter,5142,Food,1000 tonnes,-19.02,29.15,230.0,232.0,234.0,238.0,234.0,231.0,231.0,248.0,264.0,255.0,306.0,322.0,343.0,337.0,358.0,379.0,397.0,380.0,390.0,393.0,391.0,399.0,396.0,385.0,381.0,372.0,384.0,366.0,381.0,374.0,313.0,368.0,297.0,265.0,222.0,290.0,339.0,460.0,364.0,380.0,439.0,360.0,386.0,373.0,357.0,359.0,356.0,341.0,385.0,418.0,457.0,426,451,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,16529.904,X,International reliable sources,"UNDESA, Population Division – World Population..."
21473,ZWE,181,Zimbabwe,2960,"Fish, Seafood",5521,Feed,1000 tonnes,-19.02,29.15,27.0,25.0,27.0,23.0,27.0,29.0,28.0,28.0,25.0,25.0,25.0,23.0,23.0,20.0,19.0,11.0,8.0,7.0,5.0,6.0,7.0,6.0,6.0,12.0,0.0,6.0,3.0,4.0,3.0,0.0,1.0,1.0,0.0,2.0,9.0,7.0,7.0,4.0,7.0,7.0,5.0,1.0,0.0,5.0,4.0,9.0,6.0,9.0,5.0,15.0,15.0,15,15,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,16529.904,X,International reliable sources,"UNDESA, Population Division – World Population..."
21474,ZWE,181,Zimbabwe,2960,"Fish, Seafood",5142,Food,1000 tonnes,-19.02,29.15,6.0,6.0,6.0,8.0,9.0,10.0,10.0,10.0,10.0,9.0,9.0,10.0,10.0,9.0,8.0,8.0,9.0,10.0,12.0,20.0,20.0,20.0,15.0,17.0,18.0,20.0,20.0,23.0,24.0,26.0,22.0,24.0,33.0,38.0,39.0,39.0,37.0,29.0,25.0,26.0,18.0,16.0,14.0,18.0,14.0,17.0,14.0,15.0,18.0,29.0,40.0,40,40,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,16529.904,X,International reliable sources,"UNDESA, Population Division – World Population..."
21475,ZWE,181,Zimbabwe,2961,"Aquatic Products, Other",5142,Food,1000 tonnes,-19.02,29.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,16529.904,X,International reliable sources,"UNDESA, Population Division – World Population..."
21476,ZWE,181,Zimbabwe,2928,Miscellaneous,5142,Food,1000 tonnes,-19.02,29.15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,16529.904,X,International reliable sources,"UNDESA, Population Division – World Population..."

**Create new Dataframe**

In [56]:
merged_df = df_fao.merge(
    df_faostat, 
    how='left', 
    on=['area_code', 'area'])

merged_df.head()

,area_abbreviation,area_code,area,item_code_x,item_x,element_code_x,element_x,unit_x,latitude,longitude,y1961,y1962,y1963,y1964,y1965,y1966,y1967,y1968,y1969,y1970,y1971,y1972,y1973,y1974,y1975,y1976,y1977,y1978,y1979,y1980,y1981,y1982,y1983,y1984,y1985,y1986,y1987,y1988,y1989,y1990,y1991,y1992,y1993,y1994,y1995,y1996,y1997,y1998,y1999,y2000,y2001,y2002,y2003,y2004,y2005,y2006,y2007,y2008,y2009,y2010,y2011,y2012,y2013,domain_code,domain,element_code_y,element_y,item_code_y,item_y,year_code,year,unit_y,value,flag,flag_description,note
0,AFG,2,Afghanistan,2511,Wheat and products,5142,Food,1000 tonnes,33.94,67.71,1928.0,1904.0,1666.0,1950.0,2001.0,1808.0,2053.0,2045.0,2154.0,1819.0,1963.0,2215.0,2310.0,2335.0,2434.0,2512.0,2282.0,2454.0,2443.0,2129.0,2133.0,2068.0,1994.0,1851.0,1791.0,1683.0,2194.0,1801.0,1754.0,1640.0,1539.0,1582.0,1840.0,1855.0,1853.0,2177.0,2343.0,2407.0,2463.0,2600.0,2668.0,2776.0,3095.0,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population..."
1,AFG,2,Afghanistan,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,33.94,67.71,183.0,183.0,182.0,220.0,220.0,195.0,231.0,235.0,238.0,213.0,205.0,233.0,246.0,246.0,255.0,263.0,235.0,254.0,270.0,259.0,248.0,217.0,217.0,197.0,186.0,200.0,193.0,202.0,191.0,199.0,197.0,249.0,218.0,260.0,319.0,254.0,326.0,347.0,270.0,372.0,411.0,448.0,460.0,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population..."
2,AFG,2,Afghanistan,2513,Barley and products,5521,Feed,1000 tonnes,33.94,67.71,76.0,76.0,76.0,76.0,76.0,75.0,71.0,72.0,73.0,74.0,71.0,70.0,72.0,76.0,77.0,80.0,60.0,65.0,64.0,64.0,60.0,55.0,53.0,51.0,48.0,46.0,46.0,47.0,46.0,43.0,43.0,40.0,50.0,46.0,41.0,44.0,50.0,48.0,43.0,26.0,29.0,70.0,48.0,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population..."
3,AFG,2,Afghanistan,2513,Barley and products,5142,Food,1000 tonnes,33.94,67.71,237.0,237.0,237.0,238.0,238.0,237.0,225.0,227.0,230.0,234.0,223.0,219.0,225.0,240.0,244.0,255.0,185.0,203.0,198.0,202.0,189.0,174.0,167.0,160.0,151.0,145.0,145.0,148.0,145.0,135.0,132.0,120.0,155.0,143.0,125.0,138.0,159.0,154.0,141.0,84.0,83.0,122.0,144.0,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population..."
4,AFG,2,Afghanistan,2514,Maize and products,5521,Feed,1000 tonnes,33.94,67.71,210.0,210.0,214.0,216.0,216.0,216.0,235.0,232.0,236.0,200.0,201.0,216.0,228.0,231.0,234.0,240.0,228.0,234.0,228.0,226.0,210.0,199.0,192.0,182.0,173.0,170.0,154.0,148.0,137.0,144.0,126.0,90.0,141.0,150.0,159.0,108.0,90.0,99.0,72.0,35.0,48.0,89.0,63.0,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population..."

In [65]:
null_counts = merged_df.isnull().sum()

# Filter the columns to display only those with null values
columns_with_nulls = null_counts[null_counts > 0]

# Display the columns and their corresponding count of null values
print(columns_with_nulls)

rows_with_nulls = merged_df[merged_df.isnull().any(axis=1)]

# Show the rows with null values
rows_with_nulls

domain_code         247
domain              247
element_code_y      247
element_y           247
item_code_y         247
item_y              247
year_code           247
year                247
unit_y              247
value               247
flag                247
flag_description    247
note                247
dtype: int64

,area_abbreviation,area_code,area,item_code_x,item_x,element_code_x,element_x,unit_x,latitude,longitude,y1961,y1962,y1963,y1964,y1965,y1966,y1967,y1968,y1969,y1970,y1971,y1972,y1973,y1974,y1975,y1976,y1977,y1978,y1979,y1980,y1981,y1982,y1983,y1984,y1985,y1986,y1987,y1988,y1989,y1990,y1991,y1992,y1993,y1994,y1995,y1996,y1997,y1998,y1999,y2000,y2001,y2002,y2003,y2004,y2005,y2006,y2007,y2008,y2009,y2010,y2011,y2012,y2013,domain_code,domain,element_code_y,element_y,item_code_y,item_y,year_code,year,unit_y,value,flag,flag_description,note
18315,SWZ,209,Swaziland,2511,Wheat and products,5142,Food,1000 tonnes,-26.52,31.47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,22.0,27.0,28.0,25.0,31.0,34.0,41.0,45.0,48.0,43.0,44.0,44.0,38.0,39.0,38.0,26.0,30.0,31.0,33.0,36.0,36.0,43.0,46.0,42.0,38.0,44.0,50.0,53.0,51.0,53.0,55.0,57,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18316,SWZ,209,Swaziland,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,-26.52,31.47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,3.0,3.0,3.0,2.0,1.0,1.0,2.0,3.0,2.0,3.0,4.0,6.0,9.0,7.0,5.0,10.0,9.0,8.0,9.0,9.0,9.0,11.0,13.0,10.0,16.0,20.0,22.0,25.0,23.0,21.0,20.0,21.0,21.0,23.0,25,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18317,SWZ,209,Swaziland,2513,Barley and products,5521,Feed,1000 tonnes,-26.52,31.47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18318,SWZ,209,Swaziland,2513,Barley and products,5142,Food,1000 tonnes,-26.52,31.47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18319,SWZ,209,Swaziland,2514,Maize and products,5521,Feed,1000 tonnes,-26.52,31.47,6.0,7.0,6.0,6.0,6.0,7.0,13.0,10.0,12.0,13.0,21.0,24.0,18.0,23.0,19.0,19.0,14.0,19.0,13.0,19.0,21.0,12.0,11.0,37.0,37.0,22.0,22.0,33.0,25.0,23.0,19.0,23.0,22.0,21.0,31.0,25.0,30.0,32.0,35.0,33.0,35.0,34.0,33.0,32.0,37.0,31.0,32.0,32.0,33.0,37.0,36.0,38,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19073,THA,154,The former Yugoslav Republic of Macedonia,2948,Milk - Excluding Butter,5142,Food,1000 tonnes,41.61,21.75,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,201.0,202.0,207.0,188.0,172.0,166.0,200.0,219.0,240.0,228.0,226.0,234.0,262.0,257.0,276.0,321.0,328.0,308.0,321.0,324.0,327,333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19074,THA,154,The former Yugoslav Republic of Macedonia,2960,"Fish, Seafood",5521,Feed,1000 tonnes,41.61,21.75,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,12.0,18.0,13.0,14.0,18.0,8.0,12.0,11.0,9.0,8.0,6.0,3.0,4.0,3.0,1.0,1.0,2.0,2.0,2.0,1.0,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19075,THA,154,The former Yugoslav Republic of Macedonia,2960,"Fish, Seafood",5142,Food,1000 tonnes,41.61,21.75,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,5.0,6.0,8.0,8.0,9.0,8.0,9.0,9.0,9.0,7.0,10.0,10.0,11.0,10.0,12.0,13.0,12.0,12.0,12.0,12.0,11,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19076,THA,154,The former Yugoslav Republic of Macedonia,2961,"Aquatic Products, Other",5142,Food,1000 tonnes,41.61,21.75,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19077,THA,154,The former Yugoslav Republic of Macedonia,2928,Miscellaneous,5142,Food,1000 tonnes,41.61,21.75,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
df_fao[(df_fao['area_code'] == 154) & (df_fao['area'] == 'North Macedonia')]

Empty DataFrame
Columns: [area_abbreviation, area_code, area, item_code, item, element_code, element, unit, latitude, longitude, y1961, y1962, y1963, y1964, y1965, y1966, y1967, y1968, y1969, y1970, y1971, y1972, y1973, y1974, y1975, y1976, y1977, y1978, y1979, y1980, y1981, y1982, y1983, y1984, y1985, y1986, y1987, y1988, y1989, y1990, y1991, y1992, y1993, y1994, y1995, y1996, y1997, y1998, y1999, y2000, y2001, y2002, y2003, y2004, y2005, y2006, y2007, y2008, y2009, y2010, y2011, y2012, y2013]
Index: []

In [74]:
df_faostat[(df_faostat['area_code'] == 154)]

,domain_code,domain,area_code,area,element_code,element,item_code,item,year_code,year,unit,value,flag,flag_description,note
202,OA,Annual population,154,North Macedonia,511,Total Population - Both sexes,3010,Population - Est. & Proj.,2017,2017,1000 persons,2083.16,X,International reliable sources,"UNDESA, Population Division – World Population..."

In [82]:
df_fao['area_code_combination'] = list(zip(df_fao['area'], df_fao['area_code']))
df_faostat['area_code_combination'] = list(zip(df_faostat['area'], df_faostat['area_code']))

unique_in_df_fao = df_fao[~df_fao['area_code_combination'].isin(df_faostat['area_code_combination'])]['area_code_combination']

unique_in_df_faostat = df_faostat[~df_faostat['area_code_combination'].isin(df_fao['area_code_combination'])]['area_code_combination']

print("Unique combinations in df_fao not in df_faostat:\n", unique_in_df_fao.unique())
print("\nUnique combinations in df_faostat not in df_fao:\n", unique_in_df_faostat.unique())

Unique combinations in df_fao not in df_faostat:
 [('Swaziland', 209) ('The former Yugoslav Republic of Macedonia', 154)]

Unique combinations in df_faostat not in df_fao:
 [('American Samoa', 5) ('Andorra', 6) ('Anguilla', 258) ('Aruba', 22)
 ('Bahrain', 13) ('Bhutan', 18) ('British Virgin Islands', 239)
 ('Burundi', 29) ('Cayman Islands', 36) ('Channel Islands', 259)
 ('Comoros', 45) ('Cook Islands', 47)
 ('Democratic Republic of the Congo', 250) ('Equatorial Guinea', 61)
 ('Eritrea', 178) ('Falkland Islands (Malvinas)', 65)
 ('Faroe Islands', 64) ('French Guiana', 69) ('Gibraltar', 82)
 ('Greenland', 85) ('Guadeloupe', 87) ('Guam', 88) ('Holy See', 94)
 ('Isle of Man', 264) ('Libya', 124) ('Liechtenstein', 125)
 ('Marshall Islands', 127) ('Martinique', 135) ('Mayotte', 270)
 ('Micronesia (Federated States of)', 145) ('Monaco', 140)
 ('Montserrat', 142) ('Nauru', 148) ('Niue', 160)
 ('Northern Mariana Islands', 163) ('Palestine', 299) ('Palau', 180)
 ('Papua New Guinea', 168) ('Puerto Rico', 177) ('Qatar', 179)
 ('Réunion', 182) ('Saint Helena, Ascension and Tristan da Cunha', 187)
 ('Saint Pierre and Miquelon', 190) ('San Marino', 192)
 ('Seychelles', 196) ('Singapore', 200) ('Somalia', 201)
 ('South Sudan', 277) ('Eswatini', 209) ('Syrian Arab Republic', 212)
 ('North Macedonia', 154) ('Tokelau', 218) ('Tonga', 219)
 ('Turks and Caicos Islands', 224) ('Tuvalu', 227)
 ('United States Virgin Islands', 240) ('Wallis and Futuna Islands', 243)
 ('Western Sahara', 205) ('China', 351)]

### Feature Engineering

**Create New Columns**

In [ ]:
year_cols = [key.lower() for key in fao_null_values.keys()]

valid_values = merged_df[year_cols] >= 0

merged_df['years_existing'] = valid_values.sum(axis=1)
merged_df.head()

,area_abbreviation,area_code,area,item_code_x,item_x,element_code_x,element_x,unit_x,latitude,longitude,y1961,y1962,y1963,y1964,y1965,y1966,y1967,y1968,y1969,y1970,y1971,y1972,y1973,y1974,y1975,y1976,y1977,y1978,y1979,y1980,y1981,y1982,y1983,y1984,y1985,y1986,y1987,y1988,y1989,y1990,y1991,y1992,y1993,y1994,y1995,y1996,y1997,y1998,y1999,y2000,y2001,y2002,y2003,y2004,y2005,y2006,y2007,y2008,y2009,y2010,y2011,y2012,y2013,domain_code,domain,element_code_y,element_y,item_code_y,item_y,year_code,year,unit_y,value,flag,flag_description,note,years_existing
0,AFG,2,Afghanistan,2511,Wheat and products,5142,Food,1000 tonnes,33.94,67.71,1928.0,1904.0,1666.0,1950.0,2001.0,1808.0,2053.0,2045.0,2154.0,1819.0,1963.0,2215.0,2310.0,2335.0,2434.0,2512.0,2282.0,2454.0,2443.0,2129.0,2133.0,2068.0,1994.0,1851.0,1791.0,1683.0,2194.0,1801.0,1754.0,1640.0,1539.0,1582.0,1840.0,1855.0,1853.0,2177.0,2343.0,2407.0,2463.0,2600.0,2668.0,2776.0,3095.0,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population...",51
1,AFG,2,Afghanistan,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,33.94,67.71,183.0,183.0,182.0,220.0,220.0,195.0,231.0,235.0,238.0,213.0,205.0,233.0,246.0,246.0,255.0,263.0,235.0,254.0,270.0,259.0,248.0,217.0,217.0,197.0,186.0,200.0,193.0,202.0,191.0,199.0,197.0,249.0,218.0,260.0,319.0,254.0,326.0,347.0,270.0,372.0,411.0,448.0,460.0,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population...",51
2,AFG,2,Afghanistan,2513,Barley and products,5521,Feed,1000 tonnes,33.94,67.71,76.0,76.0,76.0,76.0,76.0,75.0,71.0,72.0,73.0,74.0,71.0,70.0,72.0,76.0,77.0,80.0,60.0,65.0,64.0,64.0,60.0,55.0,53.0,51.0,48.0,46.0,46.0,47.0,46.0,43.0,43.0,40.0,50.0,46.0,41.0,44.0,50.0,48.0,43.0,26.0,29.0,70.0,48.0,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population...",51
3,AFG,2,Afghanistan,2513,Barley and products,5142,Food,1000 tonnes,33.94,67.71,237.0,237.0,237.0,238.0,238.0,237.0,225.0,227.0,230.0,234.0,223.0,219.0,225.0,240.0,244.0,255.0,185.0,203.0,198.0,202.0,189.0,174.0,167.0,160.0,151.0,145.0,145.0,148.0,145.0,135.0,132.0,120.0,155.0,143.0,125.0,138.0,159.0,154.0,141.0,84.0,83.0,122.0,144.0,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population...",51
4,AFG,2,Afghanistan,2514,Maize and products,5521,Feed,1000 tonnes,33.94,67.71,210.0,210.0,214.0,216.0,216.0,216.0,235.0,232.0,236.0,200.0,201.0,216.0,228.0,231.0,234.0,240.0,228.0,234.0,228.0,226.0,210.0,199.0,192.0,182.0,173.0,170.0,154.0,148.0,137.0,144.0,126.0,90.0,141.0,150.0,159.0,108.0,90.0,99.0,72.0,35.0,48.0,89.0,63.0,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population...",51

In [ ]:
#TODO: Create another column based on the existing values of the dataframe
def calculate_average(row):
    valid_years = row[year_cols][row[year_cols] >=0]
    return valid_years.mean()

merged_df['average_production'] = merged_df.apply(calculate_average, axis=1)

merged_df[['average_production']].head()

   average_production
0         2416.098039
1          283.039216
2           87.509804
3          163.960784
4          177.470588

In [ ]:
merged_df.head()

,area_abbreviation,area_code,area,item_code_x,item_x,element_code_x,element_x,unit_x,latitude,longitude,y1961,y1962,y1963,y1964,y1965,y1966,y1967,y1968,y1969,y1970,y1971,y1972,y1973,y1974,y1975,y1976,y1977,y1978,y1979,y1980,y1981,y1982,y1983,y1984,y1985,y1986,y1987,y1988,y1989,y1990,y1991,y1992,y1993,y1994,y1995,y1996,y1997,y1998,y1999,y2000,y2001,y2002,y2003,y2004,y2005,y2006,y2007,y2008,y2009,y2010,y2011,y2012,y2013,domain_code,domain,element_code_y,element_y,item_code_y,item_y,year_code,year,unit_y,value,flag,flag_description,note,years_existing,average_production
0,AFG,2,Afghanistan,2511,Wheat and products,5142,Food,1000 tonnes,33.94,67.71,1928.0,1904.0,1666.0,1950.0,2001.0,1808.0,2053.0,2045.0,2154.0,1819.0,1963.0,2215.0,2310.0,2335.0,2434.0,2512.0,2282.0,2454.0,2443.0,2129.0,2133.0,2068.0,1994.0,1851.0,1791.0,1683.0,2194.0,1801.0,1754.0,1640.0,1539.0,1582.0,1840.0,1855.0,1853.0,2177.0,2343.0,2407.0,2463.0,2600.0,2668.0,2776.0,3095.0,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population...",51,2416.098039
1,AFG,2,Afghanistan,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,33.94,67.71,183.0,183.0,182.0,220.0,220.0,195.0,231.0,235.0,238.0,213.0,205.0,233.0,246.0,246.0,255.0,263.0,235.0,254.0,270.0,259.0,248.0,217.0,217.0,197.0,186.0,200.0,193.0,202.0,191.0,199.0,197.0,249.0,218.0,260.0,319.0,254.0,326.0,347.0,270.0,372.0,411.0,448.0,460.0,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population...",51,283.039216
2,AFG,2,Afghanistan,2513,Barley and products,5521,Feed,1000 tonnes,33.94,67.71,76.0,76.0,76.0,76.0,76.0,75.0,71.0,72.0,73.0,74.0,71.0,70.0,72.0,76.0,77.0,80.0,60.0,65.0,64.0,64.0,60.0,55.0,53.0,51.0,48.0,46.0,46.0,47.0,46.0,43.0,43.0,40.0,50.0,46.0,41.0,44.0,50.0,48.0,43.0,26.0,29.0,70.0,48.0,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population...",51,87.509804
3,AFG,2,Afghanistan,2513,Barley and products,5142,Food,1000 tonnes,33.94,67.71,237.0,237.0,237.0,238.0,238.0,237.0,225.0,227.0,230.0,234.0,223.0,219.0,225.0,240.0,244.0,255.0,185.0,203.0,198.0,202.0,189.0,174.0,167.0,160.0,151.0,145.0,145.0,148.0,145.0,135.0,132.0,120.0,155.0,143.0,125.0,138.0,159.0,154.0,141.0,84.0,83.0,122.0,144.0,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population...",51,163.960784
4,AFG,2,Afghanistan,2514,Maize and products,5521,Feed,1000 tonnes,33.94,67.71,210.0,210.0,214.0,216.0,216.0,216.0,235.0,232.0,236.0,200.0,201.0,216.0,228.0,231.0,234.0,240.0,228.0,234.0,228.0,226.0,210.0,199.0,192.0,182.0,173.0,170.0,154.0,148.0,137.0,144.0,126.0,90.0,141.0,150.0,159.0,108.0,90.0,99.0,72.0,35.0,48.0,89.0,63.0,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200,OA,Annual population,511.0,Total Population - Both sexes,3010.0,Population - Est. & Proj.,2017.0,2017.0,1000 persons,35530.081,X,International reliable sources,"UNDESA, Population Division – World Population...",51,177.470588

## `Part 2: Data Exploration`

### Feature Engineering

**Summarize Statistics**

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21477 entries, 0 to 21476
Data columns (total 78 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   area_abbreviation   21477 non-null  object
 1   area_code           21477 non-null  int64
 2   area                21477 non-null  object
 3   item_code_x         21477 non-null  int64
 4   item_x              21477 non-null  object
 5   element_code_x      21477 non-null  int64
 6   element_x           21477 non-null  object
 7   unit_x              21477 non-null  object
 8   latitude            21477 non-null  float64
 9   longitude           21477 non-null  float64
 10  y1961               21477 non-null  float64
 11  y1962               21477 non-null  float64
 12  y1963               21477 non-null  float64
 13  y1964               21477 non-null  float64
 14  y1965               21477 non-null  float64
 15  y1966               21477 non-null  float64
 16  y1967               21477 non-null  float64
 17  y1968               21477 non-null  float64
 18  y1969               21477 non-null  float64
 19  y1970               21477 non-null  float64
 20  y1971               21477 non-null  float64
 21  y1972               21477 non-null  float64
 22  y1973               21477 non-null  float64
 23  y1974               21477 non-null  float64
 24  y1975               21477 non-null  float64
 25  y1976               21477 non-null  float64
 26  y1977               21477 non-null  float64
 27  y1978               21477 non-null  float64
 28  y1979               21477 non-null  float64
 29  y1980               21477 non-null  float64
 30  y1981               21477 non-null  float64
 31  y1982               21477 non-null  float64
 32  y1983               21477 non-null  float64
 33  y1984               21477 non-null  float64
 34  y1985               21477 non-null  float64
 35  y1986               21477 non-null  float64
 36  y1987               21477 non-null  float64
 37  y1988               21477 non-null  float64
 38  y1989               21477 non-null  float64
 39  y1990               21477 non-null  float64
 40  y1991               21477 non-null  float64
 41  y1992               21477 non-null  float64
 42  y1993               21477 non-null  float64
 43  y1994               21477 non-null  float64
 44  y1995               21477 non-null  float64
 45  y1996               21477 non-null  float64
 46  y1997               21477 non-null  float64
 47  y1998               21477 non-null  float64
 48  y1999               21477 non-null  float64
 49  y2000               21477 non-null  float64
 50  y2001               21477 non-null  float64
 51  y2002               21477 non-null  float64
 52  y2003               21477 non-null  float64
 53  y2004               21477 non-null  float64
 54  y2005               21477 non-null  float64
 55  y2006               21477 non-null  float64
 56  y2007               21477 non-null  float64
 57  y2008               21477 non-null  float64
 58  y2009               21477 non-null  float64
 59  y2010               21477 non-null  float64
 60  y2011               21477 non-null  float64
 61  y2012               21477 non-null  int64
 62  y2013               21477 non-null  int64
 63  domain_code         21230 non-null  object
 64  domain              21230 non-null  object
 65  element_code_y      21230 non-null  float64
 66  element_y           21230 non-null  object
 67  item_code_y         21230 non-null  float64
 68  item_y              21230 non-null  object
 69  year_code           21230 non-null  float64
 70  year                21230 non-null  float64
 71  unit_y              21230 non-null  object
 72  value               21230 non-null  float64
 73  flag                21230 non-null  object
 74  flag_description    21230 non-null  object
 75  note                21230 non-null  object
 76  years_existing      21477 non-null  int64
 77  average_production  21373 non-null  float64
dtypes: float64(59), int64(6), object(13)
memory usage: 12.8+ MB

In [ ]:
merged_df.describe()

,area_code,item_code_x,element_code_x,latitude,longitude,y1961,y1962,y1963,y1964,y1965,y1966,y1967,y1968,y1969,y1970,y1971,y1972,y1973,y1974,y1975,y1976,y1977,y1978,y1979,y1980,y1981,y1982,y1983,y1984,y1985,y1986,y1987,y1988,y1989,y1990,y1991,y1992,y1993,y1994,y1995,y1996,y1997,y1998,y1999,y2000,y2001,y2002,y2003,y2004,y2005,y2006,y2007,y2008,y2009,y2010,y2011,y2012,y2013,element_code_y,item_code_y,year_code,year,value,years_existing,average_production
count,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21477.000000,21230.0,21230.0,21230.0,21230.0,2.123000e+04,21477.000000,21373.000000
mean,125.449411,2694.211529,5211.687154,20.450613,15.794445,162.921823,167.532383,171.443172,175.169065,181.542767,188.585510,192.285748,198.964381,203.913442,208.859012,212.180193,214.866276,223.108768,222.944406,229.055687,230.834567,238.677050,250.225683,255.274526,255.133352,260.136611,267.924803,272.877916,283.440425,287.439121,293.617870,302.135913,303.835219,310.830423,315.564883,318.955627,368.222377,378.187270,385.736090,392.936118,403.400289,409.580156,416.628859,429.062672,444.414304,451.253341,457.879033,464.995809,478.765796,485.123295,493.911114,506.014993,520.308237,522.036923,532.894166,550.714625,560.569214,575.557480,511.0,3010.0,2017.0,2017.0,4.632955e+04,45.531359,349.970340
std,72.868149,148.973406,146.820079,24.628336,66.012104,1705.176629,1723.654822,1702.649536,1703.478305,1843.230744,1921.243044,1950.546721,2002.648103,2073.775139,2125.003419,2170.408228,2215.506648,2312.519169,2164.035073,2254.508589,2220.763290,2337.665854,2522.522204,2532.574177,2497.933073,2538.049976,2681.491374,2747.069644,2837.392880,2830.725295,2956.144941,3029.916959,2961.151876,3064.330769,3141.926212,3170.481903,3428.659332,3505.221689,3661.618174,3701.017578,3906.136538,3978.799452,4090.137546,4278.872757,4612.000655,4713.189013,4829.264501,4871.515628,4961.357520,5058.833402,5122.487650,5286.212194,5483.492751,5532.614891,5707.341615,5868.935783,6047.950804,6218.379479,0.0,0.0,0.0,0.0,1.612993e+05,12.481971,3139.494617
min,1.000000,2511.000000,5142.000000,-40.900000,-172.100000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-169.000000,-246.000000,511.0,3010.0,2017.0,2017.0,5.534500e+01,0.000000,0.000000
25%,63.000000,2561.000000,5142.000000,6.430000,-11.780000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,511.0,3010.0,2017.0,2017.0,3.075647e+03,51.000000,0.215686
50%,120.000000,2640.000000,5142.000000,20.590000,19.150000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000,5.000000,6.000000,6.000000,7.000000,7.000000,7.000000,7.000000,7.000000,8.000000,8.000000,8.000000,511.0,3010.0,2017.0,2017.0,9.910701e+03,51.000000,5.235294
75%,188.000000,2782.000000,5142.000000,41.150000,46.870000,11.000000,12.000000,13.000000,13.000000,14.000000,15.000000,15.000000,16.000000,16.000000,17.000000,18.000000,18.000000,19.000000,19.000000,20.000000,20.000000,22.000000,22.000000,23.000000,24.000000,24.000000,25.000000,25.000000,27.000000,28.000000,29.000000,30.000000,31.000000,31.000000,32.000000,32.000000,49.000000,53.000000,53.000000,55.000000,56.000000,58.000000,58.000000,60.000000,64.000000,65.000000,67.000000,68.000000,72.000000,74.000000,77.000000,79.000000,80.000000,81.000000,82.000000,85.000000,88.000000,90.000000,511.0,3010.0,2017.0,2017.0,3.216549e+04,51.000000,57.745098
max,276.000000,2961.000000,5521.000000,64.960000,179.410000,112227.000000,109130.000000,106356.000000,104234.000000,119378.000000,118495.000000,118725.000000,127512.000000,134937.000000,131871.000000,143407.000000,147793.000000,142439.000000,118872.000000,123842.000000,126359.000000,128840.000000,142403.000000,147401.000000,151742.000000,157179.000000,172222.000000,182221.000000,187020.000000,188438.000000,189999.000000,190010.000000,189180.000000,192403.000000,201072.000000,193224.000000,197464.000000,202770.000000,204581.000000,208137.000000,210855.000000,221456.000000,229928.000000,255625.000000,311110.000000,327370.000000,352172.000000,354850.000000,360767.000000,373694.000000,388100.000000,402975.000000,425537.000000,434724.000000,451838.000000,462696.000000,479028.000000,489299.000000,511.0,3010.0,2017.0,2017.0,1.409517e+06,51.000000,162000.509804

**Identify Patterns**

In [ ]:
numeric_cols = year_cols + ['value', 'years_existing', 'average_production']

numeric_merged_df = merged_df[numeric_cols]
numeric_merged_df_filtered = numeric_merged_df.where(numeric_merged_df >= 0, np.nan)

print(f'Mean values: ', numeric_merged_df_filtered.mean())
print(f'Median values: ', numeric_merged_df_filtered.median())
print(f'Variance values: ', numeric_merged_df_filtered.var())
print(f'Standard Deviation values: ', numeric_merged_df_filtered.std())

Mean values:  y1961                   195.262069
y1962                   200.782250
y1963                   205.464600
y1964                   209.925577
y1965                   217.556751
y1966                   225.988962
y1967                   230.419222
y1968                   238.415487
y1969                   244.340952
y1970                   250.262237
y1971                   254.238655
y1972                   257.454677
y1973                   267.323336
y1974                   267.126547
y1975                   274.443528
y1976                   276.573364
y1977                   285.963095
y1978                   299.790166
y1979                   305.835099
y1980                   305.666072
y1981                   311.656428
y1982                   320.981157
y1983                   326.911473
y1984                   339.557866
y1985                   344.345468
y1986                   351.743227
y1987                   361.941800
y1988                   363.976363
y1989                   372.351656
y1990                   375.418115
y1991                   379.449950
y1992                   386.007760
y1993                   389.309370
y1994                   397.079607
y1995                   404.490822
y1996                   415.261922
y1997                   421.623053
y1998                   428.878505
y1999                   441.677019
y2000                   451.771819
y2001                   458.723826
y2002                   465.458964
y2003                   472.693298
y2004                   486.690742
y2005                   493.153256
y2006                   496.319328
y2007                   508.482104
y2008                   522.844898
y2009                   524.581996
y2010                   535.492069
y2011                   553.399242
value                 46329.552643
years_existing           45.531359
average_production      349.970340
dtype: float64
Median values:  y1961                    1.000000
y1962                    1.000000
y1963                    1.000000
y1964                    1.000000
y1965                    1.000000
y1966                    1.000000
y1967                    1.000000
y1968                    2.000000
y1969                    2.000000
y1970                    2.000000
y1971                    2.000000
y1972                    2.000000
y1973                    2.000000
y1974                    2.000000
y1975                    2.000000
y1976                    2.000000
y1977                    2.000000
y1978                    2.000000
y1979                    2.000000
y1980                    3.000000
y1981                    3.000000
y1982                    3.000000
y1983                    3.000000
y1984                    3.000000
y1985                    3.000000
y1986                    3.000000
y1987                    3.000000
y1988                    4.000000
y1989                    4.000000
y1990                    4.000000
y1991                    4.000000
y1992                    4.000000
y1993                    4.000000
y1994                    4.000000
y1995                    4.000000
y1996                    5.000000
y1997                    5.000000
y1998                    5.000000
y1999                    5.000000
y2000                    5.000000
y2001                    6.000000
y2002                    6.000000
y2003                    6.000000
y2004                    6.000000
y2005                    6.000000
y2006                    7.000000
y2007                    7.000000
y2008                    7.000000
y2009                    7.000000
y2010                    7.000000
y2011                    8.000000
value                 9910.701000
years_existing          51.000000
average_production       5.235294
dtype: float64
Variance values:  y1961                 3.474960e+06
y1962                 3.550457e+06
y1963                 3.463971e+06
y1964                 3.467044e+06
y1965                 4.059960e+06
y1966                 4.410959e+06
y1967                 4.546468e+06
y1968                 4.792452e+06
y1969                 5.139129e+06
y1970                 5.396179e+06
y1971                 5.629360e+06
y1972                 5.865911e+06
y1973                 6.390999e+06
y1974                 5.595174e+06
y1975                 6.073153e+06
y1976                 5.892143e+06
y1977                 6.529302e+06
y1978                 7.603663e+06
y1979                 7.663897e+06
y1980                 7.455269e+06
y1981                 7.696546e+06
y1982                 8.591989e+06
y1983                 9.017588e+06
y1984                 9.620122e+06
y1985                 9.574332e+06
y1986                 1.044247e+07
y1987                 1.097000e+07
y1988                 1.047649e+07
y1989                 1.121984e+07
y1990                 1.171572e+07
y1991                 1.192958e+07
y1992                 1.231512e+07
y1993                 1.264264e+07
y1994                 1.379621e+07
y1995                 1.409463e+07
y1996                 1.570052e+07
y1997                 1.629012e+07
y1998                 1.721467e+07
y1999                 1.884022e+07
y2000                 2.161859e+07
y2001                 2.257767e+07
y2002                 2.370352e+07
y2003                 2.412004e+07
y2004                 2.501782e+07
y2005                 2.601058e+07
y2006                 2.636637e+07
y2007                 2.807876e+07
y2008                 3.021368e+07
y2009                 3.075744e+07
y2010                 3.273086e+07
y2011                 3.461053e+07
value                 2.601746e+10
years_existing        1.557996e+02
average_production    9.856426e+06
dtype: float64
Standard Deviation values:  y1961                   1864.124336
y1962                   1884.265591
y1963                   1861.174739
y1964                   1862.000116
y1965                   2014.934333
y1966                   2100.228354
y1967                   2132.244717
y1968                   2189.166883
y1969                   2266.964627
y1970                   2322.967733
y1971                   2372.627182
y1972                   2421.964322
y1973                   2528.042608
y1974                   2365.411987
y1975                   2464.376834
y1976                   2427.373749
y1977                   2555.249955
y1978                   2757.473984
y1979                   2768.374398
y1980                   2730.433908
y1981                   2774.265032
y1982                   2931.209478
y1983                   3002.929914
y1984                   3101.632149
y1985                   3094.241689
y1986                   3231.480597
y1987                   3312.098595
y1988                   3236.741120
y1989                   3349.602911
y1990                   3422.824069
y1991                   3453.922037
y1992                   3509.290447
y1993                   3555.648726
y1994                   3714.324984
y1995                   3754.281929
y1996                   3962.388448
y1997                   4036.101905
y1998                   4149.057052
y1999                   4340.531660
y2000                   4649.579544
y2001                   4751.597094
y2002                   4868.625666
y2003                   4911.216237
y2004                   5001.782008
y2005                   5100.057036
y2006                   5134.819373
y2007                   5298.939807
y2008                   5496.697513
y2009                   5545.939303
y2010                   5721.089425
y2011                   5883.071604
value                 161299.282778
years_existing            12.481971
average_production      3139.494617
dtype: float64

In [ ]:
Q1 = numeric_merged_df_filtered.quantile(0.25)
Q3 = numeric_merged_df_filtered.quantile(0.75)
IQR = Q3 - Q1
outliers_iqr = ((numeric_merged_df_filtered < (Q1 - 1.5 * IQR)) | (numeric_merged_df_filtered > (Q3 + 1.5 * IQR))).sum()

print("Outliers :\n", outliers_iqr)

Outliers :
 y1961                 3091
y1962                 3065
y1963                 3087
y1964                 3068
y1965                 3119
y1966                 3105
y1967                 3149
y1968                 3103
y1969                 3095
y1970                 3108
y1971                 3164
y1972                 3151
y1973                 3124
y1974                 3162
y1975                 3161
y1976                 3176
y1977                 3162
y1978                 3181
y1979                 3172
y1980                 3149
y1981                 3183
y1982                 3164
y1983                 3151
y1984                 3166
y1985                 3177
y1986                 3130
y1987                 3129
y1988                 3133
y1989                 3130
y1990                 3171
y1991                 3140
y1992                 3556
y1993                 3602
y1994                 3625
y1995                 3559
y1996                 3602
y1997                 3579
y1998                 3585
y1999                 3584
y2000                 3630
y2001                 3629
y2002                 3620
y2003                 3634
y2004                 3592
y2005                 3607
y2006                 3637
y2007                 3651
y2008                 3624
y2009                 3623
y2010                 3667
y2011                 3655
value                 2380
years_existing        3539
average_production    3643
dtype: int64

**Group-Based Analysis**

In [ ]:
grouped_df = merged_df.groupby(['area_code', 'item_code_x', 'element_code_x'])

mean_group = grouped_df[numeric_merged_df_filtered.columns].mean()
print(mean_group.head())

                                      y1961  y1962  y1963  y1964  y1965  \
area_code item_code_x element_code_x
1         2511        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2513        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2514        5142             -1.0   -1.0   -1.0   -1.0   -1.0

                                      y1966  y1967  y1968  y1969  y1970  \
area_code item_code_x element_code_x
1         2511        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2513        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2514        5142             -1.0   -1.0   -1.0   -1.0   -1.0

                                      y1971  y1972  y1973  y1974  y1975  \
area_code item_code_x element_code_x
1         2511        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2513        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2514        5142             -1.0   -1.0   -1.0   -1.0   -1.0

                                      y1976  y1977  y1978  y1979  y1980  \
area_code item_code_x element_code_x
1         2511        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2513        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2514        5142             -1.0   -1.0   -1.0   -1.0   -1.0

                                      y1981  y1982  y1983  y1984  y1985  \
area_code item_code_x element_code_x
1         2511        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2513        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2514        5142             -1.0   -1.0   -1.0   -1.0   -1.0

                                      y1986  y1987  y1988  y1989  y1990  \
area_code item_code_x element_code_x
1         2511        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2513        5142             -1.0   -1.0   -1.0   -1.0   -1.0
                      5521             -1.0   -1.0   -1.0   -1.0   -1.0
          2514        5142             -1.0   -1.0   -1.0   -1.0   -1.0

                                      y1991  y1992  y1993  y1994  y1995  \
area_code item_code_x element_code_x
1         2511        5142             -1.0  539.0  544.0  476.0  497.0
                      5521             -1.0   14.0   21.0   24.0   25.0
          2513        5142             -1.0    0.0    0.0    0.0    1.0
                      5521             -1.0  115.0   63.0   58.0   61.0
          2514        5142             -1.0    0.0    0.0    0.0    0.0

                                      y1996  y1997  y1998  y1999  y2000  \
area_code item_code_x element_code_x
1         2511        5142            455.0  503.0  495.0  489.0  481.0
                      5521             10.0   32.0   58.0   55.0   78.0
          2513        5142              1.0    4.0    3.0    3.0    5.0
                      5521             79.0   31.0   48.0   46.0   15.0
          2514        5142              0.0    0.0    0.0    0.0    0.0

                                      y2001  y2002  y2003  y2004  y2005  \
area_code item_code_x element_code_x
1         2511        5142            461.0  429.0  443.0  490.0  433.0
                      5521             20.0   20.0   42.0   69.0   59.0
          2513        5142              5.0    7.0    7.0    0.0    8.0
                      5521             65.0   40.0   53.0   68.0   57.0
          2514        5142              0.0    0.0    0.0    0.0    0.0

                                      y2006  y2007  y2008  y2009  y2010  \
area_code item_code_x element_code_x
1         2511        5142            445.0  412.0  428.0  391.0  372.0
                      5521             46.0   67.0   57.0   56.0   61.0
          2513        5142              8.0    0.0    0.0    7.0   11.0
                      5521             33.0   86.0   76.0  102.0   86.0
          2514        5142              0.0    0.0    0.0    0.0    0.0

                                      y2011    value  years_existing  \
area_code item_code_x element_code_x
1         2511        5142            386.0  2930.45            20.0
                      5521             65.0  2930.45            20.0
          2513        5142              7.0  2930.45            20.0
                      5521            124.0  2930.45            20.0
          2514        5142              0.0  2930.45            20.0

                                      average_production
area_code item_code_x element_code_x
1         2511        5142                        458.45
                      5521                         43.95
          2513        5142                          3.85
                      5521                         65.30
          2514        5142                          0.00

**Correlation Analysis**

In [ ]:
numeric_cols = year_cols + ['value', 'years_existing', 'average_production']
merged_df[numeric_cols].corr(numeric_only=True)

,y1961,y1962,y1963,y1964,y1965,y1966,y1967,y1968,y1969,y1970,y1971,y1972,y1973,y1974,y1975,y1976,y1977,y1978,y1979,y1980,y1981,y1982,y1983,y1984,y1985,y1986,y1987,y1988,y1989,y1990,y1991,y1992,y1993,y1994,y1995,y1996,y1997,y1998,y1999,y2000,y2001,y2002,y2003,y2004,y2005,y2006,y2007,y2008,y2009,y2010,y2011,value,years_existing,average_production
y1961,1.000000,0.996958,0.991833,0.982647,0.986452,0.982657,0.981975,0.983398,0.984155,0.971322,0.971957,0.969846,0.966060,0.948909,0.951860,0.948459,0.946796,0.945746,0.938909,0.922294,0.926379,0.920032,0.902086,0.902261,0.898579,0.902487,0.901795,0.878239,0.882726,0.891635,0.887179,0.857201,0.850595,0.856715,0.837560,0.835570,0.829599,0.829566,0.820609,0.802400,0.791867,0.774108,0.776404,0.778281,0.769251,0.744241,0.741237,0.722006,0.714211,0.699021,0.686656,0.216483,0.042120,0.883683
y1962,0.996958,1.000000,0.996043,0.988814,0.991440,0.989030,0.987973,0.989064,0.989127,0.978550,0.978252,0.975179,0.972959,0.959264,0.962352,0.957889,0.957150,0.956047,0.948480,0.935300,0.937106,0.931028,0.914994,0.913587,0.910595,0.911908,0.911803,0.889831,0.893930,0.900542,0.895552,0.864353,0.857146,0.861410,0.843367,0.839972,0.832344,0.832532,0.822399,0.801260,0.789858,0.771480,0.773192,0.774540,0.765203,0.740054,0.736224,0.716850,0.709073,0.693857,0.681496,0.222083,0.042840,0.886991
y1963,0.991833,0.996043,1.000000,0.997229,0.995665,0.993855,0.993056,0.994569,0.991941,0.984285,0.983994,0.981998,0.978660,0.967827,0.971377,0.969250,0.965980,0.965444,0.961323,0.948316,0.951681,0.945234,0.930559,0.929519,0.927408,0.926839,0.925556,0.904802,0.908168,0.914213,0.908084,0.875277,0.867875,0.870763,0.852959,0.848620,0.839295,0.838893,0.826908,0.802429,0.789861,0.770247,0.771521,0.772249,0.762414,0.738141,0.734046,0.714503,0.706733,0.691631,0.680161,0.224848,0.044375,0.892551
y1964,0.982647,0.988814,0.997229,1.000000,0.994736,0.992261,0.992661,0.993614,0.989746,0.984840,0.984758,0.984041,0.979519,0.970844,0.975056,0.974416,0.970916,0.970223,0.968718,0.957141,0.961414,0.955225,0.942793,0.941633,0.940274,0.938516,0.936436,0.917463,0.920601,0.924858,0.918570,0.884653,0.876501,0.878486,0.860766,0.855745,0.845498,0.844835,0.831122,0.803458,0.789957,0.769376,0.770284,0.770465,0.760296,0.736842,0.732469,0.712464,0.704841,0.689775,0.678646,0.228466,0.045312,0.896035
y1965,0.986452,0.991440,0.995665,0.994736,1.000000,0.997600,0.996966,0.996646,0.996415,0.992287,0.993662,0.992209,0.988792,0.976874,0.979814,0.978692,0.976772,0.976903,0.973161,0.961279,0.962847,0.959305,0.943446,0.941993,0.937651,0.936382,0.934082,0.910126,0.913881,0.921819,0.914906,0.881339,0.872449,0.875498,0.855958,0.851412,0.841146,0.840485,0.827145,0.798902,0.785689,0.764641,0.765829,0.766568,0.756036,0.729483,0.724661,0.704384,0.696097,0.680414,0.668992,0.226097,0.043391,0.893623
y1966,0.982657,0.989030,0.993855,0.992261,0.997600,1.000000,0.998598,0.997972,0.997288,0.995417,0.994235,0.991754,0.992150,0.984137,0.986242,0.983519,0.981540,0.981675,0.976261,0.965296,0.965181,0.960212,0.946372,0.943146,0.936546,0.933411,0.931921,0.909599,0.912308,0.920532,0.913493,0.879138,0.871683,0.872729,0.855332,0.848640,0.837526,0.837483,0.823720,0.794827,0.781182,0.760217,0.760887,0.761165,0.750504,0.723608,0.718405,0.699190,0.690959,0.676018,0.665589,0.228857,0.043235,0.891702
y1967,0.981975,0.987973,0.993056,0.992661,0.996966,0.998598,1.000000,0.998139,0.997753,0.996468,0.995188,0.993810,0.993953,0.985533,0.988176,0.985719,0.984537,0.984232,0.979424,0.968653,0.969036,0.963822,0.950583,0.947499,0.940443,0.938099,0.936616,0.915211,0.918180,0.925163,0.919019,0.884731,0.877290,0.878513,0.861038,0.854910,0.843628,0.843426,0.829569,0.800492,0.786780,0.765537,0.766163,0.766634,0.755981,0.729204,0.724171,0.704625,0.696386,0.681537,0.671030,0.229090,0.043417,0.896214
y1968,0.983398,0.989064,0.994569,0.993614,0.996646,0.997972,0.998139,1.000000,0.998263,0.994801,0.994388,0.993197,0.991558,0.980821,0.984761,0.982102,0.980218,0.980590,0.976787,0.964189,0.965810,0.960493,0.945742,0.943729,0.938713,0.936760,0.935530,0.913011,0.916729,0.923901,0.917503,0.883450,0.875181,0.877248,0.858403,0.853247,0.842124,0.841844,0.828246,0.800004,0.786072,0.764762,0.765652,0.766412,0.755663,0.729350,0.724640,0.704767,0.696615,0.681332,0.670495,0.227253,0.043749,0.894926
y1969,0.984155,0.989127,0.991941,0.989746,0.996415,0.997288,0.997753,0.998263,1.000000,0.996424,0.996685,0.995105,0.993944,0.981379,0.984875,0.981769,0.981622,0.981639,0.976455,0.964389,0.964771,0.960124,0.944564,0.942089,0.936112,0.934686,0.933686,0.909650,0.913820,0.921698,0.915716,0.882120,0.873140,0.875790,0.856180,0.851512,0.840734,0.840749,0.827328,0.798758,0.785068,0.763494,0.764817,0.765748,0.754934,0.727443,0.722757,0.702729,0.694248,0.678611,0.667439,0.226229,0.043294,0.893678
y1970,0.971322,0.978550,0.984285,0.984840,0.992287,0.995417,0.996468,0.994801,0.996424,1.000000,0.997068,0.995551,0.997541,0.989513,0.991532,0.988366,0.989051,0.988041,0.981952,0.971712,0.970527,0.965888,0.953706,0.949050,0.940334,0.935868,0.934564,0.912372,0.915453,0.922725,0.916226,0.880585,0.872184,0.871574,0.853854,0.846825,0.833766,0.834369,0.819126,0.785967,0.771231,0.748638,0.749148,0.749328,0.737868,0.709489,0.704033,0.684444,0.675868,0.660824,0.650692,0.231429,0.043270,0.887289
y1971,0.971957,0.978252,0.983994,0.984758,0.993662,0.994235,0.995188,0.994388,0.996685,0.997068,1.000000,0.998284,0.996672,0.985074,0.988617,0.987408,0.987639,0.988198,0.985193,0.975086,0.974284,0.972067,0.956798,0.954380,0.947171,0.944688,0.942479,0.917420,0.921452,0.930040,0.923573,0.889221,0.879288,0.882273,0.861678,0.856918,0.845069,0.844532,0.829814,0.797508,0.783270,0.760483,0.761775,0.762191,0.750926,0.722722,0.717612,0.697144,0.688598,0.672873,0.662401,0.229217,0.043035,0.895218
y1972,0.969846,0.975179,0.981998,0.984041,0.992209,0.991754,0.993810,0.993197,0.995105,0.995551,0.998284,1.000000,0.996141,0.982306,0.986458,0.985758,0.985648,0.986509,0.984711,0.972998,0.973782,0.971200,0.954337,0.952191,0.945636,0.943508,0.940909,0.914691,0.919372,0.927303,0.921327,0.886621,0.874958,0.877658,0.855599,0.850815,0.838847,0.837931,0.822237,0.788939,0.774291,0.750373,0.751649,0.752532,0.740856,0.712541,0.707685,0.686300,0.677418,0.661168,0.650161,0.224295,0.042690,0.889353
y1973,0.966060,0.972959,0.978660,0.979519,0.988792,0.992150,0.993953,0.991558,0.993944,0.997541,0.996672,0.996141,1.000000,0.991633,0.993527,0.991022,0.992055,0.992291,0.987463,0.977788,0.976124,0.972228,0.960108,0.956187,0.946963,0.943316,0.942516,0.919490,0.922708,0.929589,0.923652,0.888470,0.880640,0.880732,0.863257,0.857613,0.844350,0.845347,0.830275,0.796954,0.782444,0.759777,0.760065,0.760306,0.748575,0.719428,0.714249,0.694325,0.686179,0.671152,0.661143,0.233056,0.042461,0.894667
y1974,0.948909,0.959264,0.967827,0.970844,0.976874,0.984137,0.985533,0.980821,0.981379,0.989513,0.985074,0.982306,0.991633,1.000000,0.997950,0.996326,0.996285,0.993553,0.987455,0.984376,0.981335,0.976042,0.971809,0.965716,0.955732,0.948430,0.948354,0.935129,0.934446,0.939934,0.933961,0.895845,0.893686,0.889393,0.880516,0.869203,0.856281,0.857902,0.843116,0.809409,0.795527,0.775220,0.773915,0.772198,0.761348,0.735479,0.729246,0.712663,0.705122,0.692382,0.684473,0.247552,0.045341,0.903709
y1975,0.951860,0.962352,0.971377,0.975056,0.979814,0.986242,0.988176,0.984761,0.984875,0.991532,0.988617,0.986458,0.993527,0.997950,1.000000,0.997898,0.997723,0.996870,0.992192,0.988675,0.986800,0.981701,0.976281,0.970897,0.961772,0.955667,0.955313,0.941118,0.941527,0.946923,0.941771,0.904572,0.900434,0.897816,0.886414,0.876282,0.863513,0.864303,0.849141,0.815401,0.800994,0.779702,0.778984,0.777650,0.766758,0.741114,0.735096,0.717600,0.709777,0.696700,0.688365,0.246537,0.044709,0.909028
y1976,0.948459,0.957889,0.969250,0.974416,0.978692,0.983519,0.985719,0.982102,0.981769,0.988366,0.987408,0.985758,0.991022,0.996326,0.997898,1.000000,0.997600,0.996677,0.994515,0.991322,0.990365,0.986262,0.979999,0.975840,0.967722,0.961876,0.960508,0.946048,0.946046,0.952935,0.946538,0.909165,0.904918,0.903071,0.891261,0.881433,0.868701,0.868716,0.853588,0.819130,0.805061,0.783674,0.783018,0.781445,0.770752,0.745808,0.739662,0.721915,0.714303,0.701071,0.693128,0.247100,0.045740,0.912258
y1977,0.946796,0.957150,0.965980,0.970916,0.976772,0.981540,0.984537,0.980218,0.981622,0.989051,0.987639,0.985648,0.992055,0.996285,0.997723,0.997600,1.000000,0.998225,0.994558,0.992443,0.990284,0.986872,0.981934,0.977299,0.968278,0.962589,0.962180,0.948072,0.948611,0.953632,0.948925,0.911807,0.907188,0.905223,0.893368,0.884268,0.871283,0.871892,0.856994,0.821946,0.807746,0.786275,0.785539,0.784091,0.773123,0.747433,0.741397,0.723659,0.715961,0.702791,0.694553,0.248858,0.044922,0.913751
y1978,0.945746,0.956047,0.965444,0.970223,0.976903,0.981675,0.984232,0.980590,0.981639,0.988041,0.988198,0.986509,0.992291,0.993553,0.996870,0.996677,0.998225,1.000000,0.997250,0.994268,0.992623,0.989807,0.983645,0.980008,0.971291,0.966443,0.965770,0.949733,0.950806,0.956825,0.952068,0.915883,0.910542,0.909869,0.896379,0.888707,0.875653,0.876106,0.861220,0.826395,0.811929,0.790015,0.789460,0.788288,0.777117,0.750834,0.744942,0.726475,0.718801,0.705466,0.697038,0.247345,0.043636,0.916445
y1979,0.938909,0.948480,0.961323,0.968718,0.973161,0.976261,0.979424,0.976787,0.976455,0.981952,0.985193,0.984711,0.987463,0.987455,0.992192,0.994515,0.994558,0.997250,1.000000,0.996420,0.996264,0.994474,0.987077,0.985497,0.978465,0.974601,0.973346,0.956568,0.958307,0.963777,0.959459,0.923968,0.917703,0.918754,0.903816,0.897568,0.884741,0.884112,0.869077,0.834014,0.819335,0.797077,0.796764,0.795490,0.784293,0.759044,0.753484,0.734450,0.726944,0.713239,0.705155,0.246366,0.044336,0.921358
y1980,0.922294,0.935300,0.948316,0.957141,0.961279,0.965296,0.968653,0.964189,0.964389,0.971712,0.975086,0.972998,0.977788,0.984376,0.988675,0.991322,0.992443,0.994268,0.996420,1.000000,0.997198,0.996189,0.992334,0.989438,0.982347,0.977062,0.976289,0.963830,0.964153,0.968350,0.964920,0.929015,0.923473,0.923679,0.911706,0.903376,0.890471,0.889541,0.874406,0.838118,0.823833,0.802227,0.801502,0.799301,0.788672,0.764740,0.758465,0.740751,0.733359,0.720614,0.713177,0.252367,0.044926,0.923329
y1981,0.926379,0.937106,0.951681,0.961414,0.962847,0.965181,0.969036,0.965810,0.964771,0.970527,0.974284,0.973782,0.976124,0.981335,0.986800,0.990365,0.990284,0.992623,0.996264,0.997198,1.000000,0.998187,0.994718,0.993634,0.988991,0.985560,0.983908,0.972425,0.972944,0.977336,0.973382,0.937757,0.933497,0.933828,0.921462,0.914101,0.902282,0.901233,0.886158,0.852080,0.838218,0.816644,0.816273,0.814085,0.803755,0.781686,0.775906,0.758093,0.750458,0.737670,0.729647,0.253504,0.045080,0.932789
y1982,0.920032,0.931028,0.945234,0.955225,0.959305,0.960212,0.963822,0.960493,0.960124,0.965888,0.972067,0.971200,0.972228,0.976042,0.981701,0.986262,0.986872,0.989807,0.994474,0.996189,0.998187,1.000000,0.995065,0.994948,0.990910,0.987725,0.985793,0.973015,0.973911,0.979342,0.974759,0.939759,0.934532,0.936251,0.922671,0.916519,0.904850,0.902861,0.888289,0.854126,0.840425,0.818925,0.818632,0.816577,0.806357,0.783915,0.777935,0.759809,0.752338,0.739204,0.731081,0.251703,0.043941,0.933131
y1983,0.902086,0.914994,0.930559,0.942793,0.943446,0.946372,0.950583,0.945742,0.944564,0.953706,0.956798,0.954337,0.960108,0.971809,0.976281,0.979999,0.981934,0.983645,0.987077,0.992334,0.994718,0.995065,1.000000,0.998307,0.993649,0.989531,0.988483,0.982729,0.982246,0.984344,0.980706,0.945027,0.945000,0.943859,0.936446,0.928928,0.917131,0.916712,0.902486,0.868863,0.855420,0.835957,0.834489,0.831039,0.821423,0.801256,0.794835,0.778835,0.772462,0.761226,0.754253,0.263401,0.043682,0.940011
y1984,0.902261,0.913587,0.929519,0.941633,0.941993,0.943146,0.947499,0.943729,0.942089,0.949050,0.954380,0.952191,0.956187,0.965716,0.970897,0.975840,0.977299,0.980008,0.985497,0.989438,0.993634,0.994948,0.998307,1.000000,0.996620,0.994196,0.992900,0.986492,0.986192,0.989089,0.985169,0.950747,0.951112,0.951894,0.943321,0.938198,0.927100,0.926448,0.913186,0.881414,0.868439,0.849257,0.848139,0.845087,0.835635,0.816149,0.810297,0.794343,0.788047,0.776656,0.769602,0.265257,0.043923,0.946998
y1985,0.898579,0.910595,0.927408,0.940274,0.937651,0.936546,0.940443,0.938713,0.936112,0.940334,0.947171,0.945636,0.946963,0.955732,0.961772,0.967722,0.968278,0.971291,0.978465,0.982347,0.988991,0.990910,0.993649,0.996620,1.000000,0.997700,0.996862,0.991626,0.991762,0.993006,0.988610,0.954881,0.955294,0.956394,0.948046,0.944457,0.934277,0.933358,0.920775,0.890438,0.877744,0.859322,0.858306,0.855363,0.846318,0.828600,0.823063,0.806503,0.800653,0.788846,0.780746,0.265455,0.044645,0.950911
y1986,0.902487,0.911908,0.926839,0.938516,0.936382,0.933411,0.938099,0.936760,0.934686,0.935868,0.944688,0.943508,0.943316,0.948430,0.955667,0.961876,0.962589,0.966443,0.974601,0.977062,0.985560,0.987725,0.989531,0.994196,0.997700,1.000000,0.998884,0.992497,0.993536,0.995374,0.992109,0.960157,0.961435,0.965209,0.955940,0.954549,0.945722,0.944760,0.933524,0.906699,0.895024,0.877213,0.876831,0.874275,0.865764,0.848721,0.843800,0.827069,0.821310,0.809471,0.800948,0.262642,0.043667,0.959395
y1987,0.901795,0.911803,0.925556,0.936436,0.934082,0.931921,0.936616,0.935530,0.933686,0.934564,0.942479,0.940909,0.942516,0.948354,0.955313,0.960508,0.962180,0.965770,0.973346,0.976289,0.983908,0.985793,0.988483,0.992900,0.996862,0.998884,1.000000,0.994701,0.995899,0.996269,0.994079,0.962497,0.964408,0.967757,0.959832,0.958642,0.949640,0.949233,0.938787,0.912259,0.900607,0.883339,0.882739,0.880299,0.871788,0.854693,0.849944,0.833452,0.827977,0.816343,0.807889,0.266710,0.043835,0.962248
y1988,0.878239,0.889831,0.904802,0.917463,0.910126,0.909599,0.915211,0.913011,0.909650,0.912372,0.917420,0.914691,0.919490,0.935129,0.941118,0.946048,0.948072,0.949733,0.956568,0.963830,0.972425,0.973015,0.982729,0.986492,0.991626,0.992497,0.994701,1.000000,0.998461,0.996047,0.995516,0.963524,0.969939,0.970911,0.969637,0.965906,0.958611,0.958430,0.949147,0.925203,0.914515,0.899915,0.898241,0.894791,0.887468,0.874229,0.869332,0.855655,0.850868,0.841381,0.834252,0.278133,0.045105,0.965077
y1989,0.882726,0.893930,0.908168,0.920601,0.913881,0.912308,0.918180,0.916729,0.913820,0.915453,0.921452,0.919372,0.922708,0.934446,0.941527,0.946046,0.948611,0.950806,0.958307,0.964153,0.972944,0.973911,0.982246,0.986192,0.991762,0.993536,0.995899,0.998461,1.000000,0.996080,0.996214,0.964993,0.969843,0.971882,0.968915,0.966504,0.959098,0.958795,0.949287,0.924728,0.913635,0.898513,0.897205,0.894274,0.886754,0.872782,0.868134,0.853393,0.848673,0.838595,0.830915,0.277803,0.044586,0.965252
y1990,0.891635,0.900542,0.914213,0.924858,0.921819,0.920532,0.925163,0.923901,0.921698,0.922725,0.930040,0.927303,0.929589,0.939934,0.946923,0.952935,0.953632,0.956825,0.963777,0.968350,0.977336,0.979342,0.984344,0.989089,0.993006,0.995374,0.996269,0.996047,0.996080,1.000000,0.997232,0.965730,0.970195,0.973572,0.968353,0.965645,0.958954,0.958476,0.948963,0.924828,0.914086,0.898487,0.898021,0.895428,0.887987,0.872920,0.868132,0.853335,0.848187,0.837828,0.830355,0.276243,0.044064,0.967345
y1991,0.887179,0.895552,0.908084,0.918570,0.914906,0.913493,0.919019,0.917503,0.915716,0.916226,0.923573,0.921327,0.923652,0.933961,0.941771,0.946538,0.948925,0.952068,0.959459,0.964920,0.973382,0.974759,0.980706,0.985169,0.988610,0.992109,0.994079,0.995516,0.996214,0.997232,1.000000,0.969014,0.973268,0.977615,0.973492,0.970270,0.964484,0.963685,0.954881,0.931251,0.920667,0.905467,0.904934,0.902410,0.895300,0.881128,0.876703,0.862311,0.857095,0.847380,0.840410,0.281238,0.044128,0.969419
y1992,0.857201,0.864353,0.875277,0.884653,0.881339,0.879138,0.884731,0.883450,0.882120,0.880585,0.889221,0.886621,0.888470,0.895845,0.904572,0.909165,0.911807,0.915883,0.923968,0.929015,0.937757,0.939759,0.945027,0.950747,0.954881,0.960157,0.962497,0.963524,0.964993,0.965730,0.969014,1.000000,0.994408,0.989280,0.980313,0.975613,0.972257,0.965519,0.955933,0.935718,0.929691,0.912136,0.910165,0.911338,0.902330,0.888452,0.882364,0.875009,0.865789,0.851600,0.847586,0.278013,0.018998,0.981020
y1993,0.850595,0.857146,0.867875,0.876501,0.872449,0.871683,0.877290,0.875181,0.873140,0.872184,0.879288,0.874958,0.880640,0.893686,0.900434,0.904918,0.907188,0.910542,0.917703,0.923473,0.933497,0.934532,0.945000,0.951112,0.955294,0.961435,0.964408,0.969939,0.969843,0.970195,0.973268,0.994408,1.000000,0.996263,0.993530,0.989379,0.986356,0.981980,0.974398,0.957881,0.951982,0.938057,0.935843,0.935476,0.927948,0.916119,0.910488,0.903911,0.896632,0.885469,0.881972,0.288494,0.019330,0.990016
y1994,0.856715,0.861410,0.870763,0.878486,0.875498,0.872729,0.878513,0.877248,0.875790,0.871574,0.882273,0.877658,0.880732,0.889393,0.897816,0.903071,0.905223,0.909869,0.918754,0.923679,0.933828,0.936251,0.943859,0.951894,0.956394,0.965209,0.967757,0.970911,0.971882,0.973572,0.977615,0.989280,0.996263,1.000000,0.995765,0.994421,0.992218,0.988327,0.982305,0.967345,0.961025,0.948177,0.947182,0.946528,0.940030,0.928362,0.923713,0.914841,0.908846,0.898585,0.894213,0.288806,0.021652,0.992305
y1995,0.837560,0.843367,0.852959,0.860766,0.855958,0.855332,0.861038,0.858403,0.856180,0.853854,0.861678,0.855599,0.863257,0.880516,0.886414,0.891261,0.893368,0.896379,0.903816,0.911706,0.921462,0.922671,0.936446,0.943321,0.948046,0.955940,0.959832,0.969637,0.968915,0.968353,0.973492,0.980313,0.993530,0.995765,1.000000,0.996746,0.995234,0.993081,0.988699,0.975775,0.970099,0.960374,0.958569,0.956828,0.951602,0.942335,0.937703,0.930687,0.926059,0.918258,0.915038,0.299968,0.023224,0.990889
y1996,0.835570,0.839972,0.848620,0.855745,0.851412,0.848640,0.854910,0.853247,0.851512,0.846825,0.856918,0.850815,0.857613,0.869203,0.876282,0.881433,0.884268,0.888707,0.897568,0.903376,0.914101,0.916519,0.928928,0.938198,0.944457,0.954549,0.958642,0.965906,0.966504,0.965645,0.970270,0.975613,0.989379,0.994421,0.996746,1.000000,0.997903,0.996552,0.993606,0.982873,0.977316,0.968030,0.966700,0.965585,0.960388,0.950480,0.946662,0.938761,0.934986,0.926841,0.922902,0.296687,0.023932,0.990160
y1997,0.829599,0.832344,0.839295,0.845498,0.841146,0.837526,0.843628,0.842124,0.840734,0.833766,0.845069,0.838847,0.844350,0.856281,0.863513,0.868701,0.871283,0.875653,0.884741,0.890471,0.902282,0.904850,0.917131,0.927100,0.934277,0.945722,0.949640,0.958611,0.959098,0.958954,0.964484,0.972257,0.986356,0.992218,0.995234,0.997903,1.000000,0.997952,0.996045,0.988457,0.983996,0.976213,0.974985,0.974617,0.970105,0.961415,0.958094,0.951294,0.947398,0.939478,0.935623,0.298190,0.023981,0.989391
y1998,0.829566,0.832532,0.838893,0.844835,0.840485,0.837483,0.843426,0.841844,0.840749,0.834369,0.844532,0.837931,0.845347,0.857902,0.864303,0.868716,0.871892,0.876106,0.884112,0.889541,0.901233,0.902861,0.916712,0.926448,0.933358,0.944760,0.949233,0.958430,0.958795,0.958476,0.963685,0.965519,0.981980,0.988327,0.993081,0.996552,0.997952,1.000000,0.998392,0.989798,0.985214,0.977886,0.977006,0.975831,0.971517,0.962643,0.960031,0.952533,0.949282,0.942398,0.938146,0.301459,0.025537,0.987655
y1999,0.820609,0.822399,0.826908,0.831122,0.827145,0.823720,0.829569,0.828246,0.827328,0.819126,0.829814,0.822237,0.830275,0.843116,0.849141,0.853588,0.856994,0.861220,0.869077,0.874406,0.886158,0.888289,0.902486,0.913186,0.920775,0.933524,0.938787,0.949147,0.949287,0.948963,0.954881,0.955933,0.974398,0.982305,0.988699,0.993606,0.996045,0.998392,1.000000,0.994530,0.990913,0.985334,0.984603,0.983285,0.979908,0.972202,0.970033,0.963023,0.960536,0.954475,0.950371,0.300861,0.025861,0.983520

**Heatmap Visualization**

## `Part 3: Data Visualization`

### Time Series Analysis

**Line Plot**

### Comparison Plot

### Geographical Visualization

**Choropleth Map**

## `Part 4: Drawing Conclusions`